# Generated by Django 5.1.5 on 2025-01-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTricker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ticker', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'crypto_tricker',
            },
        ),
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=2000)),
                ('source_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('published_at', models.DateTimeField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('tickers', models.ManyToManyField(related_name='crypto_news_tickers', to='news.cryptotricker')),
            ],
            options={
                'verbose_name_plural': 'Crypto News',
                'db_table': 'crypto_news',
                'ordering': ['-published_at'],
            },
        ),
    ]
